/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    mySidebar: [
        'intro',
        {
          type: 'category',
          label: 'Tutorial-Basics',
          items: [
              'tutorial-basics/create-a-page',
              'tutorial-basics/create-a-document',
              'tutorial-basics/create-a-blog-post',
              'tutorial-basics/deploy-your-site',
              'tutorial-basics/congratulations',
              'tutorial-basics/markdown-features',
          ],
          collapsed: false,
        },
        {
            type: 'category',
            label: 'Tutorial-Extras',
            items: [
                'tutorial-extras/manage-docs-versions',
                'tutorial-extras/translate-your-site',
            ],
            collapsed: false,
        },
        {
            type: 'category',
            label: 'CSS',
            items: [
                {
                    type: 'doc',
                    id: 'css/table',
                    label: '【CSS】 table',
                },
            ]
        },
    ],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   // 'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: [
  //         'tutorial-basics/create-a-page',
  //         'tutorial-basics/create-a-document',
  //         'tutorial-basics/create-a-blog-post',
  //         'tutorial-basics/deploy-your-site',
  //         'tutorial-basics/congratulations',
  //     ],
  //     collapsed: false,
  //   },
  //   {
  //     type: 'category',
  //     label: 'Tutorial-extra',
  //     items: [
  //       'tutorial-basics/create-a-page',
  //       'tutorial-basics/create-a-document',
  //       'tutorial-basics/create-a-blog-post',
  //       'tutorial-basics/deploy-your-site',
  //       'tutorial-basics/congratulations',
  //     ],
  //     collapsed: false,
  //   },
  // ],
};

module.exports = sidebars;
