/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    mySidebar: [
        'intro',
        // {
        //   type: 'category',
        //   label: 'Tutorial-Basics',
        //   items: [
        //       'tutorial-basics/create-a-page',
        //       'tutorial-basics/create-a-document',
        //       'tutorial-basics/create-a-blog-post',
        //       'tutorial-basics/deploy-your-site',
        //       'tutorial-basics/congratulations',
        //       'tutorial-basics/markdown-features',
        //   ],
        //   collapsed: false,
        // },
        // {
        //     type: 'category',
        //     label: 'Tutorial-Extras',
        //     items: [
        //         'tutorial-extras/manage-docs-versions',
        //         'tutorial-extras/translate-your-site',
        //     ],
        //     collapsed: false,
        // },
        {
            type: 'category',
            label: 'CSS-Tricks',
            items: [
                {
                    type: 'doc',
                    id: 'css/table',
                    label: '【CSS】 table',
                },
                {
                    type: 'doc',
                    id: 'css/input',
                    label: '【CSS】 input',
                },
                {
                    type: 'doc',
                    id: 'css/background',
                    label: '【CSS】 background',
                },
            ],
        },
        {
            type: 'category',
            label: 'HTML',
            items: [
                {
                    type: 'doc',
                    id: 'html/meta',
                    label: '【HTML】 meta',
                },
            ]
        },
        {
            type: 'category',
            label: 'NPM',
            items: [
                {
                    type: 'doc',
                    id: 'npm/npm',
                    label: '【NPM】 npm',
                },
            ]
        },
        {
            type: 'category',
            label: 'NodeJS',
            items: [
                {
                    type: 'doc',
                    id: 'node_js/nvm',
                    label: '【NodeJS】 nvm',
                },
            ]
        },
        {
            type: 'category',
            label: 'PHP',
            items: [
                {
                    type: 'doc',
                    id: 'php/extension',
                    label: '【PHP】 extension',
                },
            ]
        },
    ],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   // 'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: [
  //         'tutorial-basics/create-a-page',
  //         'tutorial-basics/create-a-document',
  //         'tutorial-basics/create-a-blog-post',
  //         'tutorial-basics/deploy-your-site',
  //         'tutorial-basics/congratulations',
  //     ],
  //     collapsed: false,
  //   },
  //   {
  //     type: 'category',
  //     label: 'Tutorial-extra',
  //     items: [
  //       'tutorial-basics/create-a-page',
  //       'tutorial-basics/create-a-document',
  //       'tutorial-basics/create-a-blog-post',
  //       'tutorial-basics/deploy-your-site',
  //       'tutorial-basics/congratulations',
  //     ],
  //     collapsed: false,
  //   },
  // ],
};

module.exports = sidebars;
