name: Argos CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  visual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force

      - name: Run server
        run: npm start > server.log 2>&1 &

      - name: Wait for server to start
        run: sleep 10

      - name: Wait for server readiness
        run: |
          for i in {1..30}; do
            curl -f http://localhost:3000 && break || sleep 2;
          done
        
      - name: Run visual tests
        run: npm run argos-chrome
